[build]
  # Comando de build
  command = "npm run build"
  # Directorio de publicación
  publish = "out"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"
  # Variables de entorno para build
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects específicos para Next.js App Router
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/security/*"
  to = "/security/index.html"
  status = 200

[[redirects]]
  from = "/propietario/*"
  to = "/propietario/index.html"
  status = 200

[[redirects]]
  from = "/inquilino/*"
  to = "/inquilino/index.html"
  status = 200

# Redirect principal para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para API calls
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"