[build]
  # Comando de build
  command = "npm run build"
  # Directorio de publicaci칩n
  publish = "out"

[build.environment]
  # Versi칩n de Node.js
  NODE_VERSION = "18"
  # Variables de entorno para build
  NEXT_TELEMETRY_DISABLED = "1"

# Configuraci칩n para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets est치ticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para API calls
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"